
NORMAL = 0
SUSPICIOUS = 1
MARKED = 2
FILTER_OUT = 3

PROJECT_CONFIG_FILENAME = 'project.conf'
PACKETS_DIRNAME = 'packets'
SERVICES_DIRNAME = 'services'
SERVICE_CONFIG_FILENAME = 'service.conf'
APPLY_SCRIPT_FILENAME = 'apply-script.py'

CAPTURE_FILENAME = 'capture.pcap'
MAX_CAPTURE_FILESIZE = 64*1000
